### ISSUE TITLE
Withdraw loops over dividend history

### ISSUE THREAD

**Issue by wjmelements** [yarrumretep/dividend-token#2]
Instead of having a history of dividends, you could have an increasing total counter. Your eligible dividends are the difference between the total counter and the counter your shares last collected their dividend.

**Comment by yarrumretep** [comment]
The issue is that you need to know what shares each holder held at the time of each dividend.  Here the goal is that each dividend holder gets the dividends for the shares they held at the moment of the dividend.  If they transfer their shares away the dividends stay with the original holder.

**Comment by wjmelements** [comment]
One option would be to update transfer:
- Update recipient to current dividend
- Pay any relevant dividend for the update if the recipient had prior shares
- Pay any unclaimed dividend to prior owner

This would make withdraw cheaper and transfer more expensive

**Comment by yarrumretep** [comment]
I think the bookkeeping for that route would be prohibitive.  You would have to know what % of an accounts holding is eligible for a historical dividend.  Also, doesn't save looping b/c this contract handles different ERC20s and ETH.

Try it!  PRs welcome.  As Linus T. says "Talk is cheap - show me the code"  :-)

**Comment by wjmelements** [comment]
The tokens requirement prohibits this approach.
